wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.3
    framework: huggingface
    huggingface_version: 4.31.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689036736.718125
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 83
      2:
      - 1
      - 11
      - 41
      - 49
      - 51
      - 55
      - 71
      - 83
      3:
      - 23
      4: 3.8.16
      5: 0.15.3
      6: 4.31.0.dev0
      8:
      - 5
input_pertubation:
  desc: null
  value: 0
pretrained_model_name_or_path:
  desc: null
  value: CompVis/stable-diffusion-v1-4
revision:
  desc: null
  value: null
dataset_name:
  desc: null
  value: ydshieh/coco_dataset_script
dataset_config_name:
  desc: null
  value: '2017'
data_dir:
  desc: null
  value: /remote-home/songtianwei/research/diffusion_model_my/data
train_data_dir:
  desc: null
  value: null
image_column:
  desc: null
  value: image_path
caption_column:
  desc: null
  value: caption
max_train_samples:
  desc: null
  value: null
output_dir:
  desc: null
  value: my_train_results/ydshieh/coco_dataset_script/2023-07-11
cache_dir:
  desc: null
  value: null
seed:
  desc: null
  value: null
resolution:
  desc: null
  value: 224
center_crop:
  desc: null
  value: true
random_flip:
  desc: null
  value: true
train_batch_size:
  desc: null
  value: 6
num_train_epochs:
  desc: null
  value: 1
max_train_steps:
  desc: null
  value: 15000
gradient_accumulation_steps:
  desc: null
  value: 1
gradient_checkpointing:
  desc: null
  value: true
learning_rate:
  desc: null
  value: 1.0e-06
scale_lr:
  desc: null
  value: false
lr_scheduler:
  desc: null
  value: constant
lr_warmup_steps:
  desc: null
  value: 0
snr_gamma:
  desc: null
  value: null
use_8bit_adam:
  desc: null
  value: true
allow_tf32:
  desc: null
  value: false
use_ema:
  desc: null
  value: true
non_ema_revision:
  desc: null
  value: null
dataloader_num_workers:
  desc: null
  value: 0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_weight_decay:
  desc: null
  value: 0.01
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
push_to_hub:
  desc: null
  value: false
hub_token:
  desc: null
  value: null
hub_model_id:
  desc: null
  value: null
logging_dir:
  desc: null
  value: logs
mixed_precision:
  desc: null
  value: null
report_to:
  desc: null
  value: wandb
local_rank:
  desc: null
  value: -1
checkpointing_steps:
  desc: null
  value: 500
checkpoints_total_limit:
  desc: null
  value: null
resume_from_checkpoint:
  desc: null
  value: null
enable_xformers_memory_efficient_attention:
  desc: null
  value: false
noise_offset:
  desc: null
  value: 0
validation_epochs:
  desc: null
  value: 5
tracker_project_name:
  desc: null
  value: text2image-fine-tune
